amazon.dynamodb.endpoint=http://localhost:8000/
amazon.aws.accesskey=test
amazon.aws.secretkey=test
aws.region=us-central-1

spring.data.dynamodb.entity2ddl.auto=create-only

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration


twilio.account_sid=AC13650e8b85e9673334f081fcd8a8e8d3
twilio.auth_token=bc328e56d37d2d75403a09815fdde579
twilio.phone_number=+14155238886


jwt.secret.key=IAUZyIU+LyPh9oc8H3OPb0afqPybBSxv1/X6tnLvci9HofGb2AhtHs9RhLH0NJxt
jwt.time.expiration=3600000