spring.application.name=auth-service
server.port=0

amazon.dynamodb.endpoint=http://localhost:8000/
amazon.aws.accesskey=test
amazon.aws.secretkey=test
aws.region=us-central-1

spring.data.dynamodb.entity2ddl.auto=create-only

jwt.secret.key=cHJvamVjdCBzZWFyY2ggZW5naW5lIGJldGEgY3ViYSA3MTE=
jwt.time.expiration=3600000

#Eureka client
eureka.client.service-url.default-zone=http://eureka:password@localhost:8761/eureka
eureka.instance.instance-id=${spring.application.name}:${spring.application.instance_id:${random.value}}