amazon.dynamodb.endpoint=http://localhost:8000/
amazon.aws.accesskey=test
amazon.aws.secretkey=test
aws.region=us-central-1

spring.data.dynamodb.entity2ddl.auto=create-only

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration


twilio.account_sid=AC13650e8b85e9673334f081fcd8a8e8d3
twilio.auth_token=35eadf4a1a631eff4b6264e6bfdbd6e8
twilio.phone_number=+14155238886