version: '3.8'
services:
  ### Dynamo DB for users
  db-users:
    image: amazon/dynamodb-local
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    expose:
      - "8000"
    volumes:
      - ./user-data:/data
    command:
      - "-jar DynamoDBLocal.jar -sharedDb -dbPath /data"


volumes:
  user-data:



