spring.application.name=user-service
server.port=0

amazon.dynamodb.endpoint=http://localhost:8000/
amazon.aws.accesskey=test
amazon.aws.secretkey=test
aws.region=us-central-1

spring.data.dynamodb.entity2ddl.auto=create-only

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration


jwt.secret.key=IAUZyIU+LyPh9oc8H3OPb0afqPybBSxv1/X6tnLvci9HofGb2AhtHs9RhLH0NJxt
jwt.time.expiration=3600000

#Eureka client
eureka.client.service-url.default-zone=http://eureka:password@localhost:8761/eureka
eureka.instance.instance-id=${spring.application.name}:${spring.application.instance_id:${random.value}}