spring.application.name=verification-service
server.port=0

amazon.dynamodb.endpoint=http://localhost:8000/
amazon.aws.accesskey=test
amazon.aws.secretkey=test
aws.region=us-central-1

spring.data.dynamodb.entity2ddl.auto=create-only

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

aws.secret-key=C0zi2qRAjmN195+QZwgT4nNFPkFAL5lITd7J6j3f
aws.access-key=AKIARLR46GUNK52O3ZD7
aw.region=us-east-1

jwt.secret.key=IAUZyIU+LyPh9oc8H3OPb0afqPybBSxv1/X6tnLvci9HofGb2AhtHs9RhLH0NJxt
jwt.time.expiration=3600000

#Eureka client
eureka.client.service-url.default-zone=http://eureka:password@localhost:8761/eureka
eureka.instance.instance-id=${spring.application.name}:${spring.application.instance_id:${random.value}}